# Generated by Django 5.0.3 on 2024-03-29 08:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_comment_like_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='lesson'),
        ),
        migrations.AlterField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'lesson')},
        ),
    ]
